### PR TITLE
chore: apply black fixes

### PR DESCRIPTION
**Pull request by ghickman**
Not sure why these weren't picked up locally or in CI for #766 so here we are

### CODE REVIEW

**Review by lucyb — APPROVED** [review]

**Comment by evansd** [comment]
I think this might have been part of the Github Actions "special time". It looks like only the Semantic PR check ran on the previous PR and nothing else:
github com_opensafely-core_cohort-extractor_pull_766

**Comment by ghickman** [comment]
_sigh_

Yep, that will be it for CI!  I'm still surprised pre-commit didn't pick it up locally though 🤔

**Comment by evansd** [comment]
I think that makes sense: pre-commit runs before the commit, so a commit which upgrades the version of Black is going to get checked with the previous version of Black.

**Comment by ghickman** [comment]
#766 includes a change to the pre-commit config though, that would have run with the updated version

**Pull request merged**
